retail:
 target: dev
 outputs:
  dev:
    type: bigquery
    method: service-account
    keyfile: /usr/local/airflow/include/gcp/service_account.json
    project: crucial-cycling-439407-m4
    dataset: retail
    threads: 1
    timeout_seconds: 300
    location: US